# Generated by Django 2.2.16 on 2022-03-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.Genre'),
            preserve_default=False,
        ),
    ]
