# Generated by Django 2.2.16 on 2022-03-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220325_1813'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_name_owner',
        ),
    ]
